baseURL = "https://cv.tolecnal.net/"
languageCode = "en-us"
title = "Jostein Elvaker Haande Resume"

theme = "devlite-cv"

disableRSS = true
disableSitemap = true
disable404 = true

[params]
description = "Jostein Elvaker Haande Resume"
author = "Jostein Elvaker Haande"
title = "Jostein Elvaker Haande Resume"
github_username = "tolecnal"
# Profile section
[params.profile]
name = "Jostein Elvaker Haande"
tagline = "Systems Engineer / IT Manager"
avatar = "profile.jpg"

# Contact section
[params.contact]
enable = true

[[params.contact.list]]
class = "location"
icon = "fa-location-arrow"
url = "#"
title = "Norway"

[[params.contact.list]]
class = "email"
icon = "fa-envelope"
url = "mailto:tolecnal@tolecnal.net"
title = "tolecnal@tolecnal.net"

[[params.contact.list]]
class = "website"
icon = "fa-globe"
url = "//tolecnal.net"
title = "tolecnal.net"

[[params.contact.list]]
class = "linkedin"
icon = "fa-linkedin"
url = "//www.linkedin.com/in/josteinhaande/"
title = "@josteinhaande/"

[[params.contact.list]]
class = "github"
icon = "fa-github"
url = "//github.com/tolecnal"
title = "github.com/tolecnal"

[[params.contact.list]]
class = "twitter"
icon = "fa-twitter"
url = "//twitter.com/tolecnal"
title = "@tolecnal"

[[params.contact.list]]
class = "instagram"
icon = "fa-instagram"
url = "//instagram.com/jehaande/"
title = "@jehaande"

# Languages section
[params.language]
enable = true
title = "Languages"

[[params.language.list]]
language = "Norwegian"
level = "Native"

[[params.language.list]]
language = "English"
level = "Fluent"

[[params.language.list]]
language = "German"
level = "Rusty"

# Experiences section
[params.experiences]
enable = true
icon = "fa-briefcase"
title = "Work experiences"

[[params.jobs.list]]
position = "IT Manager"
dates = "January 2021 - Present (3 years 3 months)"
company = "ayfie AS, Oslo, Norway"
details = "Responsible for everything IT, from hardware to software. On Premise and Cloud resources in AWS, OVH and Azure. Office 365. Liason with the development team."

[[params.jobs.list]]
position = "IT Manager / Senior Solutions Specialist"
dates = "May 2019 - January 2021 (1 year 9 months)"
company = "ayfie AS, Oslo, Norway"
details = "Responsible for IT, On Premise and Cloud. Performing advanced training with customers and partners. Liason with the development team."

[[params.jobs.list]]
position = "Senior Systems Engineer"
dates = "February 2018 - May 2019 (1 year 4 months)"
company = "ayfie AS, Oslo, Norway"
details = "Planning and performing installations of in-house developed software to customers. Partly responsible for internal IT functions. Partner training."

[[params.jobs.list]]
position = "Systems Engineer"
dates = "February 2014 - February 2018 (4 years)"
company = "ayfie AS, Oslo, Norway"
details = "Planning and performing installations of in-house developed software to customers. Partly responsible for internal IT functions."

[[params.jobs.list]]
position = "Product Consultant"
dates = "June 2008 - January 2014 (5 years 7 months)"
company = "SystemPartner International AS, Oslo, Norway"
details = "Planning and performing installations of software used in the hospitality industriy. Performing on-site hardware installations, and on-site training of staff."

[[params.jobs.list]]
position = "Bartender"
dates = "September 2006 - May 2008 (1 year 9 months)"
company = "Goggen Sportspub, Drammen, Norway"
details = "Customer service and sales."

[[params.jobs.list]]
position = "Receptionist"
dates = "March 2005 - August 2005 (6 months)"
company = "Alcudia Port Suites, Pourto del Alcudia, Spain"
details = "Worked in the reception, dealing with bookings, check-ins and general customer service."

[[params.jobs.list]]
position = "Waiter"
dates = "August 2002 - August 2006 (4 years)"
company = "Jonas B. Gundersen, Drammen, Norway"
details = "Worked in the reception, dealing with bookings, check-ins and general customer service."

# Experiences section
[params.education]
enable = true
icon = "fa-graduation-cap"
title = "Education"

[[params.school.list]]
title = "Network Engineer"
dates = "August 2001 - August 2002"
school = "Akademiet, Drammen, Norway"
details = "Network and infrastructure planning."

[[params.school.list]]
title = "Service Electrician"
dates = "August 1995 - August 1998"
school = "St. Hallvard VGS and Tinius Olsen VGS"
details = "Service Electrician for office and computer equipment. Repairing, maintaining and building computers."

# Projects section
[params.projects]
enable = true
icon = "fa-archive"
title = "Personal Projects"
intro = "This is part of my projects that I have developed and maintain. You can find many of my other projects in my GitHub profile"

[[params.projects.list]]
title = "wp2hugo"
url = "https://github.com/tolecnal/wp2hugo"
tagline = "A Python CLI application that converts a WordPress WXR backup file to MD files usable by Hugo."

[[params.projects.list]]
title = "ansible-role-pihole-doh"
url = "https://github.com/tolecnal/ansible-role-pihole-doh"
tagline = "Ansible role to deploy Pihole, using Cloudflare's DNS proxy service to use DNS over HTTPS."

[[params.projects.list]]
title = "ansible-role-ohmyzsh"
url = "https://github.com/tolecnal/ansible-role-ohmyzsh"
tagline = "Ansible role to deploy and configure Oh My Zsh with the Powerlevel 10K theme."

[[params.projects.list]]
title = "ansible-role-tmux_npm"
url = "https://github.com/tolecnal/ansible-role-tmux_npm"
tagline = "Ansible role to install and configure tmux with the TPM plugin manager, and some nice extras."

[[params.projects.list]]
title = "ansible-role-nvchad"
url = "https://github.com/tolecnal/ansible-role-nvchad"
tagline = "Ansible role to install and configure neovim with a default configuration, and required APT and Python packages."

[params.tools]
enable = true
icon = "fa-laptop"
title = "Languages and Tools"

[[params.tools.list]]
badge = "Python"
skill = "Python"
style = "flat-square"
color = "black"
logo = "Python"

[[params.tools.list]]
badge = "PowerShell"
skill = "PowerShell"
style = "flat-square"
color = "black"
logo = "PowerShell"

[[params.tools.list]]
badge = "GNU%20Bash"
skill = "Bash"
style = "flat-square"
color = "black"
logo = "gnubash"

[[params.tools.list]]
badge = "zsh"
skill = "zsh"
style = "flat-square"
color = "black"
logo = "zsh"

[[params.tools.list]]
badge = "perl"
skill = "perl"
style = "flat-square"
color = "black"
logo = "perl"

[[params.tools.list]]
badge = "Apache"
skill = "Apache"
style = "flat-square"
color = "black"
logo = "Apache"

[[params.tools.list]]
badge = "Nginx"
skill = "Nginx"
style = "flat-square"
color = "black"
logo = "Nginx"

[[params.tools.list]]
badge = "Markdown"
skill = "Markdown"
style = "flat-square"
color = "black"
logo = "Markdown"

[[params.tools.list]]
badge = "Windows"
skill = "Windows"
style = "flat-square"
color = "black"
logo = "Windows"

[[params.tools.list]]
badge = "Linux"
skill = "Linux"
style = "flat-square"
color = "black"
logo = "Linux"

[[params.tools.list]]
badge = "macOS"
skill = "macOS"
style = "flat-square"
color = "black"
logo = "macos"

[[params.tools.list]]
badge = "Debian"
skill = "Debian"
style = "flat-square"
color = "black"
logo = "Debian"

[[params.tools.list]]
badge = "Ubuntu"
skill = "Ubuntu"
style = "flat-square"
color = "black"
logo = "Ubuntu"

[[params.tools.list]]
badge = "RedHat"
skill = "Red%20Hat"
style = "flat-square"
color = "black"
logo = "redhat"

[[params.tools.list]]
badge = "PostgreSQL"
skill = "PostgreSQL"
style = "flat-square"
color = "black"
logo = "PostgreSQL"

[[params.tools.list]]
badge = "MySQL"
skill = "MySQL"
style = "flat-square"
color = "black"
logo = "MySQL"

[[params.tools.list]]
badge = "Microsoft SQL Server"
skill = "Microsoft SQL Server"
style = "flat-square"
color = "black"
logo = "microsoftsqlserver"

[[params.tools.list]]
badge = "MongoDB"
skill = "MongoDB"
style = "flat-square"
color = "black"
logo = "MongoDB"

[[params.tools.list]]
badge = "Redis"
skill = "Redis"
style = "flat-square"
color = "black"
logo = "Redis"

[[params.tools.list]]
badge = "Icinga"
skill = "Icinga"
style = "flat-square"
color = "black"
logo = "Icinga"

[[params.tools.list]]
badge = "Active Directory"
skill = "Active Directory"
style = "flat-square"
color = "black"
logo = "ActiveDirectory"

[[params.tools.list]]
badge = "Azure AD"
skill = "Azure AD"
style = "flat-square"
color = "black"
logo = "AzureAD"

[[params.tools.list]]
badge = "Office 365"
skill = "Office 365"
style = "flat-square"
color = "black"
logo = "Office365"

[[params.tools.list]]
badge = "Docker"
skill = "Docker"
style = "flat-square"
color = "black"
logo = "Docker"

[[params.tools.list]]
badge = "Amazon AWS"
skill = "Amazon AWS"
style = "flat-square"
color = "black"
logo = "amazonaws"

[[params.tools.list]]
badge = "Microsoft Azure"
skill = "Microsoft%20Azure"
style = "flat-square"
color = "black"
logo = "Microsoft-Azure"

[[params.tools.list]]
badge = "Cloudflare"
skill = "Cloudflare"
style = "flat-square"
color = "black"
logo = "Cloudflare"

[[params.tools.list]]
badge = "DigitalOcean"
skill = "DigitalOcean"
style = "flat-square"
color = "black"
logo = "DigitalOcean"

[[params.tools.list]]
badge = "Git"
skill = "Git"
style = "flat-square"
color = "black"
logo = "git"

[[params.tools.list]]
badge = "Ansible"
skill = "Ansible"
style = "flat-square"
color = "black"
logo = "ansible"

[[params.tools.list]]
badge = "GitHub"
skill = "GitHub"
style = "flat-square"
color = "black"
logo = "GitHub"

[[params.tools.list]]
badge = "GitLab"
skill = "GitLab"
style = "flat-square"
color = "black"
logo = "GitLab"

[[params.tools.list]]
badge = "Jenkins"
skill = "Jenkins"
style = "flat-square"
color = "black"
logo = "jenkins"

[[params.tools.list]]
badge = "Vim"
skill = "Vim"
style = "flat-square"
color = "black"
logo = "vim"

[[params.tools.list]]
badge = "Neovim"
skill = "Neovim"
style = "flat-square"
color = "black"
logo = "vim"

[[params.tools.list]]
badge = "Visual Studio Code"
skill = "Visual Studio Code"
style = "flat-square"
color = "black"
logo = "visualstudiocode"
